### ISSUE TITLE
Version 0.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/SWAPY#19]
```
Version 0.5


```

Original issue reported on code.google.com by `moden4dr...@gmail.com` on 8 Jan 2012 at 12:34
* Blocked on: #7, #13, #18, #24

**Comment by vasily-v-ryabov** [comment]
How about moving all references to 0.5.x features to the milestone?

**Comment by moden-py** [comment]
A good idea, move all the linked issues and close this one.
