### ISSUE TITLE
Not able to access menu bar items and Tool strip items

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/SWAPY#35]
```
What steps will reproduce the problem?
1.In my application, I don't see the menu items such as File--saveas or file 
-->Exit. 
2.I am not able to access toolstrip items also
3.

What is the expected output? What do you see instead?
Should be able to access menu items and 

What version of the product are you using? On what operating system?

Windows 7
Please provide any additional information below.
Attached screensot


```

Original issue reported on code.google.com by `simply.a...@gmail.com` on 16 May 2013 at 4:20

Attachments:
* [menustrip_items.jpg](https://storage.googleapis.com/google-code-attachments/swapy/issue-35/comment-0/menustrip_items.jpg)
* [Toolstrip_items.jpg](https://storage.googleapis.com/google-code-attachments/swapy/issue-35/comment-0/Toolstrip_items.jpg)

**Comment by moden-py** [comment]
automation lib(pywinauto) limitation problem.
