### ISSUE TITLE
it seems not handle Chinese Character in the left window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/SWAPY#36]
```
I can see `???` only.
Maybe it also cannot handle utf-8 character?
```

Original issue reported on code.google.com by `iamapla...@gmail.com` on 11 Jan 2015 at 7:00

**Comment by moden-py** [comment]
Unicode converting '.encode('cp1251', 'replace')' causes such problems.

**Comment by moden-py** [comment]
https://github.com/pywinauto/SWAPY/releases/tag/0.4.5
