### ISSUE TITLE
Delete/edit already generated commands

### ISSUE THREAD

**Issue by airelil** [pywinauto/SWAPY#53]
It would be helpful if there was a possibility to edit commands in the Editor window. Quite often I want to change or delete the generated commands. Maybe if not full edition but at least a kind of "undo" to remove last command and put another instead.

**Comment by moden-py** [comment]
Agree with you, but edition is not a trivial task. Now all the code redraw each time new action added. It needed to control `app.Kill_()` all the time at the end. Switching Start/Connect also impose a restriction on the editing.
Going to solve the restriction within task - "Run code in SWAPY". But I have not yet decided when it will be.

Sure "Undo" would be very useful. There are some ways how it will look.
1. A button somewhere on the window.
2. A main menu item. I have long want to add the main menu with "Save code to file", "About", "Refresh", "Restart", etc. options.

I prefer the second one.

Lets discuss the name. "Undo" means the last action will be reverted. But it is not possible. Only "The last action code" can be removed. The action have already performed and cannot(easily) be undo.  A test window state may be changed by the action but the editor is cleared by "Undo".
We shout mark that only code of the last action may be "Undo". May be "Clear last command" would be a good candidate for the option's name.

**Comment by airelil** [comment]
I agree, the feature is complicated, especially if we say that SWAPY is not a code generator but just an object inspector. ```Clear last command``` sounds good for me. Maybe it could be placed into a context menu when Editor window is right clicked ? You could place your other Editor-related commands there as well. For example ```Save code to file```. 
I also thought that ```Clear the code``` would also be useful. (Fits well to the Editor's context menu too) Maybe this is the easiest command to start with. All you need is just remove the code from the Editor and its internal representation.
