### ISSUE TITLE
Win7 32bit cannot run swapy

### ISSUE THREAD

**Issue by aristotll** [pywinauto/SWAPY#76]
I tried many times, including using executed as administrator.

**Comment by vasily-v-ryabov** [comment]
That may be a similar problem:

```
If Win8.1 or Win10 denies you to run SWAPY executable,
just click "More info" link on the warning window and then choose "Run anyway".
The binaries are not digitally signed yet.
```

See [post in the blog](http://guiautomation.blogspot.com/2015/11/new-code-generator-in-swapy.html).

**Comment by aristotll** [comment]
Sorry for a late reply, I click the exe, but windows just gives no message ,even no errors.Just nothing happens.

**Comment by aristotll** [comment]
I download on sourceforge, and there is no problem .Maybe something wrong with the exe.Thanks.
