### ISSUE TITLE
SWAPY cannot display Chinese.

### ISSUE THREAD

**Issue by aristotll** [pywinauto/SWAPY#77]
I tried to use English path or English softwares.
But there are times when I have to use Chinese ones which cannot be displayed right.
Even swapy can displays the characters in Unicode just like in my picture.

But there are always ?? on left columns. I wonder if this small problem can be solved. Thanks.

OK, I cannot upload the picture in github(after many times), please visit here 
https://www.flickr.com/photos/138319215@N03/

**Comment by moden-py** [comment]
Thank @aristotll for the description. Can you upload an empty text file with Chinese name like at the picture? I would test it on my side.
Thanks.

**Comment by aristotll** [comment]
"娱乐" @moden-py. Thanks.

**Comment by moden-py** [comment]
@aristotll, I managed to reproduce the problem.
It seems like I do extra unicode - string encoding.
Please try the fix from our CI server
32bit - https://ci.appveyor.com/project/moden-py/swapy-pwvh2/build/job/10x48a4nqbrhexjl/artifacts
64bit - https://ci.appveyor.com/project/moden-py/swapy-pwvh2/build/job/raq5k4fc86u77snj/artifacts

**Comment by aristotll** [comment]
It works. @moden-py. Thanks.

**Comment by moden-py** [comment]
@aristotll, thank you too.
