### ISSUE TITLE
SWAPY list object has no attribute encode

### ISSUE THREAD

**Issue by aristotll** [pywinauto/SWAPY#78]
I update the version for displaying correct Chinese.
However, SWAPY new version has bug the version before does not have.

When clicking the statureBar of a soft,
there is such error:

 Traceback error:file:"C:\projects\swapy-pwvh2\build\swapy\out00-PYZ.pyz_mainframe",line
 407, in _update Attribute error:  'list' object has no attribute 'encode'

Thanks.

**Comment by moden-py** [comment]
@aristotll, I do not see relation between those two bugs, I need your help.
Could you try to reproduce `list` problem again. Is it easy to reproduce?
I cannot figure out how `list` passed through `str` conversion with `UnicodeEncodeError` in 405 in the code (even if the list was a list of unicode values).
If you manage to reproduce it again, please provide the broken field value using a stable version of SWAPY.
If no, it can be a rare problem caused by a thread synchronization issue.

Thanks a lot.

**Comment by aristotll** [comment]
I managed to reproduce it with version 0.4.7.
I tries to access the field value, but the soft just broke down whenever I clicked the name.
I can only tell from the screenshot some of the field value is. 
Here is my screenshot . 

It seems it has an encoding problem,because I can only reproduce it when clicking something with Chinese.
https://www.flickr.com/photos/138319215@N03/23210509333
https://www.flickr.com/photos/138319215@N03/23754821341
https://www.flickr.com/photos/138319215@N03/23541598120

I tried three times with similar results.
Thanks a lot.

**Comment by moden-py** [comment]
Hope I caught the problem.
I almost sure the `Fonts` property has Chinese symbols. This causes the known `__repr__` problem.
https://bugs.python.org/issue5876
I have no apps with Unicode in the Fonts property, but I managed to artificially invoke the issue.

Here is the fix, please try also `Copy value`, `Copy all` and `Copy Unicode value` on the problem property(I almost sure it is `Fonts`).
https://ci.appveyor.com/project/moden-py/swapy-pwvh2/build/job/vuiyeae2b134qpj7/artifacts
https://ci.appveyor.com/project/moden-py/swapy-pwvh2/build/job/5dur7g3jtd8tjf84/artifacts

Unfortunately, Python2.X does not work well with unicode.
For example the same property would look:
Python2 `Access names: [u'Notepad', u'\u5a31\u4e50 \u2014 \u0411\u043b\u043e\u043a\u043d\u043e\u0442', u'\u5a31\u4e50 \u2014 \u0411\u043b\u043e\u043a\u043d\u043e\u0442Notepad']`
Python3 `Access names: ['Notepad', '娱乐 — Блокнот', '娱乐 — БлокнотNotepad']`

I am planning to port SWAPY on Python 3.X in future.

**Comment by aristotll** [comment]
@moden-py
The problem is solved perfectly.
I think the  Access names is not a big problem, as long as I can get access to the names from left columns.
Thank you very much.

**Comment by moden-py** [comment]
Cool, this is a good news!
Will merge the latest fixes in the next release.

**Comment by changhyuk91** [comment]
Hi guys I just started programming(5days), so I really need help getting this problem fixed. I am getting the same error as aristotll and more. 

 "Traceback error:file:"C:\projects\swapy-pwvh2\build\swapy\out00-PYZ.pyz_mainframe",line
407, in _update Attribute error: 'list' object has no attribute 'encode'"

Additional errors when I press application.start and application.connect respectively:
![image](https://cloud.githubusercontent.com/assets/17735784/13624646/e234cf2e-e564-11e5-8a85-e43f47f39037.png)

![image](https://cloud.githubusercontent.com/assets/17735784/13624653/ec9879de-e564-11e5-9080-35de8e694112.png)

I am using the korean language so I think I am getting the same problem. It seems like you guys found the remedy so I re-downloaded and installed SWAPY32bit.exe from the Github, but the error persists. I dont know how Aristotll got his work. 

Thanks so much in advance, you guys are awesome. 

I am currently using Python 3.5

**Comment by moden-py** [comment]
Hi @changhyuk91 , thank you for the report.
It seems like a new bug, so I've opened appropriate [issue ](https://github.com/pywinauto/SWAPY/issues/84)
Please, track the problem there.
