### ISSUE TITLE
ImportError: No module named 'exceptions'

### ISSUE THREAD

**Issue by pravic** [pywinauto/SWAPY#87]
```
> py -3 swapy-ob.py
Traceback (most recent call last):
  File "swapy-ob.py", line 27, in <module>
    import _mainframe
  File "D:\usr\dev\emsi\source\testing\swapy\_mainframe.py", line 24, in <module>
    import exceptions
ImportError: No module named 'exceptions'
```

win7 x64, Python 3.5.2 x64.

**Comment by moden-py** [comment]
SWAPY is not Python3 compatible, [details](https://github.com/pywinauto/SWAPY/issues/79).
Unfortunately too little chance to move on Python3 in the nearest future.
You still may run SWAPY sources under Python 2.7.X or use "compiled" [binary](https://github.com/pywinauto/SWAPY/releases).

**Comment by pravic** [comment]
Thanks.
