### ISSUE TITLE
Is any plans for further developing to match with pywinauto 0.6.0 ?

### ISSUE THREAD

**Issue by GhostFromHeaven** [pywinauto/SWAPY#88]
I am looking forward to it.

**Comment by moden-py** [comment]
Hi @GhostFromHeaven, I did not finished UIA support fo SWAPY
https://github.com/moden-py/SWAPY/tree/UIASWAPY
It is unlikely that I will have enough time in the near future.
So, any PR is welcome!

**Comment by GhostFromHeaven** [comment]
Thank you @moden-py , and I will fork that.
