### ISSUE TITLE
Is there some way to change tabwidget

### ISSUE THREAD

**Issue by sincerefly** [pywinauto/SWAPY#89]
There is software written by QT, on the top of the software, there is a tab widget, I'm not find SWAPY have options to change the tab, And is there something way to change the tab, thank you

**Comment by moden-py** [comment]
SWAPY not intended to change any window's content.
If your software opensource, you probably may change all in the sources. Then compile the changes.

**Comment by vasily-v-ryabov** [comment]
Hi @sincerefly if you want to switch tab (probably not change) for Qt app, you must use `Application(backend="uia")`. Unfortunately SWAPY doesn't support "uia" backend. So you have to write some code. For GUI object inspection please use `Inspect.exe` as a spy tool (can be found [here on GitHub](https://github.com/blackrosezy/gui-inspect-tool)) and read [the Getting Started Guide for pywinauto](https://pywinauto.readthedocs.io/en/latest/getting_started.html).

Examples for pywinauto contain [wireshark.py](https://github.com/pywinauto/pywinauto/blob/master/examples/wireshark.py) (WireShark is a Qt5 app so this example should be also a good guidance for you though there is no tab switching as I remember).

**Comment by sincerefly** [comment]
Thanks @moden-py  @vasily-v-ryabov
