### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Syuukensyou** [pywinauto/SWAPY#90]
how do I pyinstaller the project? 
The follows cant work:
`pyinstaller -F swapy-ob.py`
but the .exe cant work .

**Comment by moden-py** [comment]
The question is not quite clear.
The easiest way is to use EXE from https://github.com/pywinauto/SWAPY/releases/tag/0.4.8

**Comment by Syuukensyou** [comment]
How do I compile this program in python3.x environment to generate exe file?@moden-py 
I run the program in the pycharm, but the following bug has occurred:
![treeitemdata bug](https://user-images.githubusercontent.com/18436076/39511905-9fe330a2-4e21-11e8-917a-5adfc49dd3f5.png)

**Comment by vasily-v-ryabov** [comment]
Hi @Syuukensyou I don't think SWAPY will run on Python 3.x. If you were interested in contribution to the project, I'd suggest taking a look at [py_inspect](https://github.com/pywinauto/py_inspect) prototype of the cross-platform GUI inspect tool which is built on new pywinauto architecture and has much smaller code base. It can switch between pywinauto's backends (SWAPY can't) and can run on Python 3.5 at least. Only code generator is not implemented yet. This is not the highest priority for the team, so if you could continue this tool development it would significantly improve learning curve for new pywinauto users. What do you think?

**Comment by Syuukensyou** [comment]
I am still very interested in similar projects, so I will try  if there is time. Thank you for your patient answer.
